### ISSUE TITLE
How to add borders to table

### ISSUE THREAD

**Issue by xdf103** [scanny/python-pptx#203] opened 2016-03-26 01:35 UTC
Hi,

Tables are now created without borders. Is there anyway to add borders to the tables?

**Comment by smcpherson** [comment] 2016-11-04 22:10
+1 for this one. My specific use case would be for creating borderless tables. 

(via powerpoint you would select a table then select  Table Design -> Borders -> "No Borders")

**Comment by scanny** [comment] 2018-09-23 22:30
duplicate of #71

**Closed by scanny** 2018-09-23 22:30 UTC
Labels: table
