### ISSUE TITLE
There is no item named 'ppt/notesMasters/NULL

### ISSUE THREAD

**Issue by nanshihui** [scanny/python-pptx#406] opened 2018-07-16 02:52 UTC
i try to open a ppt, however, it doesn't work. any volunteer
`
Traceback (most recent call last):
    prs = Presentation(orgin_path)
  File "/usr/local/lib/python2.7/dist-packages/pptx/api.py", line 30, in Presentation
    presentation_part = Package.open(pptx).main_document_part
  File "/usr/local/lib/python2.7/dist-packages/pptx/opc/package.py", line 122, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/usr/local/lib/python2.7/dist-packages/pptx/opc/pkgreader.py", line 36, in from_file
    phys_reader, pkg_srels, content_types
  File "/usr/local/lib/python2.7/dist-packages/pptx/opc/pkgreader.py", line 69, in _load_serialized_parts
    for partname, blob, srels in part_walker:
  File "/usr/local/lib/python2.7/dist-packages/pptx/opc/pkgreader.py", line 104, in _walk_phys_parts
    phys_reader, part_srels, visited_partnames):
  File "/usr/local/lib/python2.7/dist-packages/pptx/opc/pkgreader.py", line 104, in _walk_phys_parts
    phys_reader, part_srels, visited_partnames):
  File "/usr/local/lib/python2.7/dist-packages/pptx/opc/pkgreader.py", line 101, in _walk_phys_parts
    blob = phys_reader.blob_for(partname)
  File "/usr/local/lib/python2.7/dist-packages/pptx/opc/phys_pkg.py", line 109, in blob_for
    return self._zipf.read(pack_uri.membername)
  File "/usr/lib/python2.7/zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "/usr/lib/python2.7/zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'ppt/notesMasters/NULL' in the archive"

`

**Comment by scanny** [comment] 2021-08-11 19:43
Duplicate of #206

**Closed by scanny** 2021-08-11 19:43 UTC
