### ISSUE TITLE
how to set multi-axis for chart

### ISSUE THREAD

**Issue by zhaowei699** [scanny/python-pptx#402] opened 2018-07-10 02:41 UTC
Hi PPTX Team
I am trying to study pptx module to output presentation for CAE, but I can’t find an example for setting multi-axis.
Do you have example for it? Thanks a lot
For example:
I want to set a chart and contain three vertical axis and one horizontal axis.
![example](https://user-images.githubusercontent.com/30488215/42486276-bfcfe5c6-842d-11e8-81c8-7dc18d2132cc.png)

**Comment by jbq** [comment] 2018-07-10 05:44
What you are looking for is probably combo charts, see
https://github.com/scanny/python-pptx/issues/338#issuecomment-382145684

**Comment by jbq** [comment] 2018-07-11 06:09
You can find the `add_subchart()` method and other changes required here: https://github.com/jbq/python-pptx/commit/ddffc2839e3f909b3bf8acdc8fe80ecfe63492a6

**Comment by zhaowei699** [comment] 2018-07-11 06:18
Hi Again
You means I need to replace the file (..\anaconda3440\envs\python36\Lib\site-packages\pptx\chart\chart.py) of my python by your modified file.

**Comment by jbq** [comment] 2018-07-11 06:38
Exactly

**Comment by zhaowei699** [comment] 2018-07-13 02:04
thanks jbq a lot
It is a really good idea and function to extend pptx by "add_subchar".

**Comment by Ramboisme** [comment] 2019-12-11 05:57
Hello, I still don't understand what you said. Can we talk about it? @zhaowei699

**Comment by zhaowei699** [comment] 2019-12-11 07:01
Hi Ramboisme
Thanks for your attention
I only want to know how to set multiple axis for one plot and how to insert different curves which belong to different axis in the same plot.

See the picture in the top, there are three Y axis in one plot, several curves belong to the first Y axis, several curves belong to the second axis, …

**Comment by Ramboisme** [comment] 2019-12-11 07:12
I wonder if you can use pptx to draw a graph with histogram and line? @zhaowei699

**Comment by zhaowei699** [comment] 2019-12-11 09:26
You are right. I think I should advise Microsoft to improve it first.

**Comment by Ramboisme** [comment] 2019-12-11 09:29
After I change the bottom layer again, I report a mistake.   
'CategoryWorkbookWriter' object has no attribute 'x_values_ref'

**Comment by zhaowei699** [comment] 2019-12-11 09:36
For the first picture, I use the CAE software Animator to generate pptx, it can set multiple axis. The Animator use other method, because I can't edit data again in power point, every curves became the single placeholder. In any case, thank you very much. I don't care this problem any more.

**Comment by Ramboisme** [comment] 2019-12-11 09:56
好吧，麻烦您啦。

**Comment by GundappaGavandi** [comment] 2020-03-01 18:41
Hi,

I am looking for combo chart solution, 
does anyone have any idea to solve it?

**Comment by scanny** [comment] 2021-12-29 19:50
Duplicate of #141.

**Closed by scanny** 2021-12-29 19:50 UTC
