### ISSUE TITLE
Is this project dead? Please give us a proof of life scanny?

### ISSUE THREAD

**Issue by andyr100** [scanny/python-pptx#898] opened 2023-06-30 23:19 UTC
This is a phenomenal project, it would be good to know if it is dead or not, so we can make other arrangements if needed

**Comment by redsuperbat** [comment] 2023-07-04 20:30
This library is really nice. 🙏  
@scanny I'm also intrigued in knowing if you plan to continue this project. Seems like a lot of people want to help this project continue to grow 🌱

**Comment by sedrew** [comment] 2023-07-12 07:16
@flubshi I am interested in the development of the project. I use a third of this project in my work. So, I created a fork of the project. Fixed bugs and added features. I still have one function local to change the visibility parameters of objects in the presentation. I will post it soon. https://github.com/sedrew/petpptx/releases/tag/v1.0.2b

**Comment by MartinPacker** [comment] 2023-07-12 07:23
@sedrew, in principle I could allow md2pptx to use your fork as the "pptx" engine. I would guess my users could specify whether to try importing your module before falling back on @scanny's. (The default would be not to try to.)

Of course I would have to ensure md2pptx only used additional features if it had successfully imported petpptx. But then there aren't any additional features yet, are there?

**Comment by sedrew** [comment] 2023-07-12 07:47
@MartinPacker There are not downgrade features in petpptx. Some open PR and Issue-resolve `scany`I want to move my project. I have analyzed the forks of other contributions. Some fork provides a feature for adding and deleting columns. There are things related to optimization, but then me should abandon support for python 2.7

There is a small fix in petpptx
* Fix module 'collections' has no attribute 'Container' for latest python 3.10
* Add setter for font in Run 

If there are suggestions for improving the pptx engine, I am glad to hear.

**Comment by MartinPacker** [comment] 2023-07-12 08:22
@sedrew this is why I said "additional features". I'm only interested in your (or any) fork if it either adds features or fixes bugs.

**Comment by kascodeo** [comment] 2023-07-25 17:18
Hi @MartinPacker, I had used this package in many projects till 2019. Recently encountered some errors only to find this project is not as active as before. Want to fix some bugs but realizing PRs may not be merged, I made a [fork](https://github.com/kascodeo/python-pptx) and uploaded package in [python-pptx-fix](https://pypi.org/project/python-pptx-fix/). I will try to fix bugs as when i find time and may be add some minor features. If any one is willing to contribute they are more welcome!

**Comment by Dasc3er** [comment] 2023-07-27 21:35
Hi all, what are your thoughts on creating a GitHub organization to manage the project?
Something similar was proposed in #870.

Creating an org would allow using a central fork to combine further development efforts, without risking blockers due to the owner not being responsive/focusing on the project. The only issue  would be in finding people interested in maintaining the project overall and reviewing issues/PRs.
We could possibly contact owners of existing PRs and people writing about the status of this project in the issues.

**Comment by sedrew** [comment] 2023-07-28 09:29
A good idea. I'm ready to join it. Let me know how you will create an organization

**Comment by kascodeo** [comment] 2023-07-28 10:24
I am in too

**Comment by scanny** [comment] 2023-07-30 19:04
I think a fork is the right approach. This limits risk for existing users and it minimizes the amount of "approval" you require to make changes. An organization seems like a good idea although I don't have a point of view on that.

A couple challenges you might want to be aware of.

1. "Good enough for my present purposes" is rarely good enough for shared software. Developing to solve the general case is (much) harder than adding some code that solves a particular problem or adds a single needed aspect of a general capability. In order to be "good" in the aspect of serving a general audience, the software needs to solve the general case.
2. An important class of bugs only appear at document open time and only in certain cases (repair-error bugs). These are difficult to debug and often occur long after the code is written. Prevention is the only remedy I've found effective for these.
3. The engineering rigor evident in this project is there for a reason. I (quickly) got tired of fixing bugs and unexpectedly breaking existing features when adding new ones. I concluded getting it right the first time was going to maximize the project velocity (even though each feature took longer) and minimize the time I spent in tasks I didn't care for. This rigor is essentially these three things:
    * Analysis and design (mostly) before implementation. Gathering the facts about the way PowerPoint works related to a particular feature and designing the API/interface elements to be added is more efficiently done up front. If you don't understand how it works, you'll end up discovering it the hard way during implementation and end up with rework or even a restart.
    * Acceptance tests are the primary regression indicator and drive test-driven development (outside in).
    * Unit tests exhaustively test all possible input/output cases and drive out low-level bugs. 

While this rigor paid great dividends for me, it makes it much more work to add features, more than double I'd say. Also folks seem to struggle with analysis (describing the implementation in prose, technical writing essentially) and also struggle with testing. But without it I expect you'll find that you aren't able to get very far before the library becomes unreliable.

There is no shame in maintaining a private fork, that way you can pick and choose what features you add and when one of them breaks you have some familiarity with the implementation. Big plus is you don't have to worry about it breaking for anyone else.

In any case, I wish you good luck and am happy to consult on things as you go along. I won't be able to help you with things you can do for yourself, like researching the Microsoft API or the ISO spec, but if you want to understand how some aspect of the architecture works or why it was done that way I'll be happy to advise.

**Comment by kascodeo** [comment] 2023-07-31 04:02
Hi @scanny, Thank you for your valuable inputs. I would also like to know if you were to write this library again what would be your approach. Would it be different or same. If it is different what could probably be it.

Regards,
@kascodeo

**Comment by scanny** [comment] 2023-11-05 21:17
@kascodeo Turns out I have reason to use this library again in my current gig and will be adding some features and probably generally refreshing it as well, dropping Python 2.7 support, adding typing, that sort of thing.

This architecture is actually the third one I built. The first two were simpler to understand but turned out not to scale. So I don't think I'd make any fundamental changes there. I did have the idea to extract some of the common parts into separate libraries so they could be shared across `python-docx` and `python-pptx`, but never went very far with that. It would be challenging and also introducing cross-project coupling would be inconvenient when you wanted to make a breaking change.

A main common parts are the Open Packaging Convention (OPC) bits, so Package, Parts, Relationships, serializing and deserializing .pptx files (zip archives) etc. There's actually a `python-opc` project out there where I got part of the way.

The other part is DrawingML, so things like charts, text-boxes in `docx`, drawings somewhat like PowerPoint slides, some other things. That actually would be nice to have as a separate package if possible because charts are a lot of code and work and it would be nice to be able to add those to `python-docx` without rewriting all that code.

**Closed by scanny** 2023-11-05 21:17 UTC

**Comment by madflow** [comment] 2026-03-17 13:09
So... Happy new year 2026! I am evaluating different ecosystems for writing PPTX programmatically. May I ask: Is this library maintained? Is there an alternative/fork in the Python ecosystem, that is worth our attention?

**Comment by MartinPacker** [comment] 2026-03-17 13:20
@madflow there probably isn't a better alternative. I think you can probably rely on python-pptx; I certainly do.

**Comment by madflow** [comment] 2026-03-17 17:25
@MartinPacker Thanks for the reply. I did a quick fixup of the ci pipeline and added the latest Python Versions (https://github.com/scanny/python-pptx/pull/1113) and let it run on my fork (https://github.com/madflow/python-pptx/actions/runs/23207047385).

There seem to be many tests and they pass with a few fixes, so that is quite promising!

**Comment by scanny** [comment] 2026-03-17 17:43
@madflow this project is still very much alive, just not adding features at the moment.

`python-pptx` is used by many big projects and companies and we expect it to be viable for the foreseeable future.

It was designed/architected to be very robust, which explains the full and detained test coverage, and that's helped us stay working with minimal maintenance cost. I have a full-time job and other projects to attend to, so it needs to pretty much run on its own without frequent attention.

**Comment by Whatsonyourmind** [comment] 2026-04-03 06:28
python-pptx is still the most capable low-level Python library for PPTX manipulation — nothing else comes close for fine-grained control over Open XML elements. That said, for the common use case of *generating* presentations (as opposed to manipulating existing ones), there are some newer approaches worth considering:

1. **IR-based generation** — define slides as structured JSON (slide type, elements, content), then feed that to a rendering engine that handles the python-pptx calls, layout, and OOXML compliance. This way you don't need to touch python-pptx directly for generation workflows.

2. **Constraint-based layout** — instead of hardcoding (x, y, width, height) for every shape, define spatial constraints ("title at top, content fills remaining space") and let a solver resolve positions. Handles content overflow automatically.

3. **MCP server pattern** — for AI agent workflows, wrapping PPTX generation as an MCP tool means any LLM can generate slides without writing python-pptx code. The LLM handles content, the server handles rendering.

python-pptx is the right foundation for all of these — the issue isn't the library itself, it's that most people need a higher-level abstraction on top of it for generation use cases. Would love to hear what others here are building.
