### ISSUE TITLE
Secondary Axis missing in Charts

### ISSUE THREAD

**Issue by vijetaiot** [scanny/python-pptx#618] opened 2020-05-10 06:16 UTC
For column or bar charts, often we end up having **secondary axis** to depict additional features. I tried various ways, but couldn't figure out a way to add Secondary-axis to either a column or bar charts. Is there any possible way or work-around to add this. 
any help would be highly appreciated!

**Comment by Mynkj1996** [comment] 2020-05-26 11:33
I also want to know how to add a secondary axis in python-pptx. If it's not yet implemented then please let us know the other way or can share his/her code .help would be highly appreciated!

@scanny please help us

**Comment by willkim1** [comment] 2020-07-20 16:45
This is not implemented yet, but you can add it to build\lib\pptx\chart\axis.py

I suggest just copying the a chart that already has a secondary axis and replacing the values.

**Comment by scanny** [comment] 2021-12-29 19:49
Duplicate of #141.

**Closed by scanny** 2021-12-29 19:49 UTC
