### ISSUE TITLE
feature: adding data tables to charts

### ISSUE THREAD

**Issue by soumyand** [scanny/python-pptx#726] opened 2021-08-06 14:30 UTC
how to create COLUMN_CLUSTERED or COLUMN_STACKED charts that include automatically-generated data tables with the legend like below using python-pptx library.

![image](https://user-images.githubusercontent.com/33153116/128525931-0cc89141-0eea-41cb-9eb5-f9f79fb664fa.png)

https://stackoverflow.com/questions/68683062/adding-data-tables-to-column-clustered-or-column-stacked-charts-with-python-pptx

**Comment by scanny** [comment] 2021-08-06 16:44
Example XML in #373

**Comment by soumyand** [comment] 2021-08-07 10:24
I am trying to insert chart in a pptx slide chart placeholder like below- it is giving error -"lxml.etree.XMLSyntaxError: Namespace prefix a on bodyPr is not defined, line 8, column 16" .

placeholder = slide.placeholders[11]
graphic_frame = placeholder.insert_chart(XL_CHART_TYPE.COLUMN_CLUSTERED, chart_data)
chart=graphic_frame.chart

chart.plots._plotArea.append(etree.fromstring(dTable))

here dTable is

dTable = """
<c:dTable xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart">
<c:showHorzBorder val="1"/>
<c:showVertBorder val="1"/>
<c:showOutline val="1"/>
<c:showKeys val="1"/>
<c:txPr>
<a:bodyPr/>
<a:lstStyle/>
<a:p>
<a:pPr rtl="0">
<a:defRPr sz="1000" baseline="0"/>
</a:pPr>
<a:endParaRPr lang="fr-FR"/>
</a:p>
</c:txPr>
</c:dTable>
"""

It is giving below error
chart.plots._plotArea.append(etree.fromstring(dTable))
File "src\lxml\etree.pyx", line 3237, in lxml.etree.fromstring
File "src\lxml\parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
File "src\lxml\parser.pxi", line 1777, in lxml.etree._parseDoc
File "src\lxml\parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
File "src\lxml\parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
File "src\lxml\parser.pxi", line 725, in lxml.etree._handleParseResult
File "src\lxml\parser.pxi", line 654, in lxml.etree._raiseParseError
File "", line 8
lxml.etree.XMLSyntaxError: Namespace prefix a on bodyPr is not defined, line 8, column 16

**Comment by scanny** [comment] 2021-08-11 19:57
Duplicate of #373

**Closed by scanny** 2021-08-11 19:57 UTC
Labels: chart
