### ISSUE TITLE
feature: ignore package relationships pointing to "NULL"

### ISSUE THREAD

**Issue by PuneethaPai** [scanny/python-pptx#497] opened 2019-04-24 12:55 UTC
Code
`pres = Presentation('file.pptx')`

Relevant Error:
`File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1428, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1467, in open
    zinfo = self.getinfo(name)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1395, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'ppt/slides/NULL' in the archive"`

**Comment by PuneethaPai** [comment] 2019-04-24 12:58
Some of the answers found in net:
https://stackoverflow.com/questions/55578790/using-python-pptx-what-conditions-could-a-powerpoint-have-that-give-keyerror

Please help as I could find many solutions when Image not present, Chart not present.
In my case I am suspecting a slide itself was improperly deleted by making reference point to `NULL`.

**Comment by marcomilov** [comment] 2019-06-08 08:02
I had a similar issue, where a third party tool was used to create charts in PowerPoint. Every time it deleted something, instead or correctly doing it it just replaced the relationship with NULL. While PowerPoint ignores this, python-pptx does not. In my case, opening the file PowerPoint and saving it again solved the issue for me because PowerPoint removes the relationship. Maybe that works for you as well?

**Comment by PuneethaPai** [comment] 2019-06-11 11:09
Thanks for the reply. Its a great work and very useful library.

Several issues like `ppt/drawings/NULL`, etc do get resolved when opened and saved once.

But I found only this error `ppt/slides/NULL` to stick by even with opening and saving work around.

I found deleting some random slides helped. But its not scalable.

Actually amongst 200 odd ppts I have only one was getting this issue. So not a big blocker.

Thanks and I appreciate your work.

**Comment by scanny** [comment] 2019-06-11 16:53
I'll leave this one open and see about just skipping relationships that appear like this. That way they'll just disappear on `Presentation.save()` and should allow loading those without error.

**Comment by PDWest** [comment] 2019-06-19 14:10
I'm getting this (or similar (There is no item named 'ppt/slides/NULL' in the archive")) error while opening a large, legacy (evolved over many ppt versions) file.  I've tried deleting a few suspect slides and re-saving, but the error persists.  My program simply opens pptx files, mines information from the notes field and then produces a separate output file.  But, I cannot process this particular pptx file.  Any work-around ideas would be appreciated, or even suggestions on how to find and fix the problem in the pptx file.

**Comment by scanny** [comment] 2019-06-19 16:40
If you're willing to patch the XML by hand here's a rough approach:

1. Expand the .pptx file (aka. "package", which is a zip archive) using `opc-diag`:

   ```bash
   $ opc extract problematic.pptx temp
   ```
2. Open the file `ppt/_rels/presentation.xml.rels`, look for the offending line, delete it, and save the file. You can use something like `grep` or `ag` (silver-searcher) to look for any others in the other `.rels` files if you want and get rid of those too, but I expect it's just here.

3. Repackage the .pptx file using `opc-diag`:

   ```bash
   $ opc repackage temp fixed.pptx
   ```

`opc-diag` is a utility developed as a companion to `python-pptx` and `python-docx` and can be installed and uninstalled with `pip`

```bash
$ pip install opc-diag
```

**Comment by PDWest** [comment] 2019-06-19 21:01
Thanks for the help on this.  I installed opc-diag, but it doesn't like my file either (or I'm somehow using it incorrectly).  I could paste the error log in here, but this seems like the wrong place for that.  That said, if I rename my pptx file by adding .zip to the end, I can open the archive up in textWrangler and look at /ppt/_rels .  I don't have any experience looking at these things, but nothing jumps out to me as being mal-formed.  All the reference pairs look pretty much like this:
Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide61.xml"/><Relationship Id="rId84" 

What should I be looking for in the 'offending line'?

Again, thanks for the help

**Comment by scanny** [comment] 2019-06-20 02:38
look for `... Target="ppt/slides/NULL"/>`. If you don't find it in that .rels file look in the others you can find around the directory hierarchy.

**Comment by PDWest** [comment] 2019-06-20 03:51
I cannot find the string "NULL" anywhere in the file...

But: I have found a work around.  I saved my pptx file in .odp format, opened and saved it in Libre Office, opened the odp file in Powerpoint and then saved back to pptx and the error is gone and my notes miner program works!  Surprisingly, although the file looks very bad in Libre Office, when back in Powerpoint,  it looks OK. 

Thanks for the help with this!

**Comment by crystalfp** [comment] 2021-04-24 07:12
Please fix the problem in the library. The proposed workarounds are really labor intensive. 
And the bug is a showstopper for migrating a working (and kludging) solution based on `win32com.client` I have to `python-pptx`. Thanks!

**Comment by PuneethaPai** [comment] 2021-05-01 03:25
This issue is fixed through this PR: https://github.com/scanny/python-pptx/pull/468 #468 . Thanks to @paulusm  for this.

**But the PR has merge conflict. Either @scanny  or @paulusm can fix and merge this.**

**Comment by crystalfp** [comment] 2021-05-01 06:37
Yes, please, merge this PR! In the meantime I applied the two small changes to my installed package (bad bad, I know). This solved the problem and now I can continue my exploration of this beautiful package.

**Comment by crystalfp** [comment] 2021-05-03 12:10
@PuneethaPai the conflict reduces to have in one file the line where the change should be applied shifted down 3 or 4 lines. So really simple to apply. Please @scanny merge it!

**Comment by scanny** [comment] 2021-08-11 19:44
Duplicate of #206

**Closed by scanny** 2021-08-11 19:44 UTC
