### ISSUE TITLE
feature: speaker notes

### ISSUE THREAD

**Issue by choldil** [scanny/python-pptx#181] opened 2015-09-19 01:42 UTC
Hello Scanny,

I'm new to GitHub so my apologies if this is not the right place to ask for this.
I have to prepare PowerPoint slides from an Access database, all text or number fields.
My idea was to first save it as an Excel spreadsheet and then extract the 
data and build the text slides with python-pptx, but for me it's mandatory that one
of the text fields has to go as speaker notes.
Do you think it is feasible? or that you might implement it in the future?

Thank you very much,

**Comment by scanny** [comment] 2015-11-28 03:55
Closed as duplicate of #122.

**Closed by scanny** 2015-11-28 03:55 UTC
