### ISSUE TITLE
Inserting slides at a specific position in presentation

### ISSUE THREAD

**Issue by sarwatfatimam** [scanny/python-pptx#274] opened 2017-04-01 18:09 UTC
Hi, 

I was wondering if the feature for adding a slide at a specific position has been developed. The docs read, "At the time of writing it’s the only way to add a slide, but sooner or later I expect someone will want to insert one in the middle, and when they post a feature request for that I expect I’ll add an insert_slide (idx, ...) method." 
If this feature has not yet been developed, can someone please add this feature?

**Comment by blaze33** [comment] 2017-04-24 13:26
There's a way to do this:

```python
class PresentationBuilder(object):

    presentation = Presentation("your_presentation.pptx")

    @property
    def xml_slides(self):
        return self.presentation.slides._sldIdLst  # pylint: disable=protected-access

    def move_slide(self, old_index, new_index):
        slides = list(self.xml_slides)
        self.xml_slides.remove(slides[old_index])
        self.xml_slides.insert(new_index, slides[old_index])

    # also works for deleting slides
    def delete_slide(self, index):
        slides = list(self.xml_slides)
        self.xml_slides.remove(slides[index])
```

Now you can add a slide to the end (default behavior) and use `move_slide(-1, x)` to insert it at the right place.

**Comment by scanny** [comment] 2017-04-24 19:14
Duplicate of #68

**Closed by scanny** 2017-04-24 19:14 UTC

**Comment by alleks8** [comment] 2017-05-05 06:59
Can I get some help with using this functions?
For some reason I don`t manage to insert slides at given position.
