### ISSUE TITLE
GraphicFrame

### ISSUE THREAD

**Issue by alphazw** [scanny/python-pptx#448] opened 2018-10-03 15:15 UTC
I realized that in current version of powerpoint, the smartart object been used very often, however, in current release, it seems has nothing to do with it, what I want to express is, some smart object has many text on it, we can get text on some shapes, but can not get text from the SmartObj.

Any plan the package will includes this features?

**Comment by scanny** [comment] 2018-10-03 15:39
Duplicate of #83. No current plans to work on this, but maybe one day.

**Closed by scanny** 2018-10-03 15:39 UTC

**Comment by alphazw** [comment] 2018-10-05 00:43
Thank you Scanny for your response, and I am sorry made a duplicated issue of #83 , the #83 discussion do provide some insight and thinking about my questions.

What I am want to do is not intending to create any SmartObj with python-pptx, I just want to read the text from the SmartObj and play with those text, read and change them may be, will not create a new SmartObj from scratch with the python-pptx.

Thank you for making this great package for parsing the pptx doc in Python. I appreciate on that, it makes works easier.

**Comment by alphazw** [comment] 2018-10-05 12:55
I read the #83 and other issues posted before, I aware that according to `slide.part.blob` could get the XML original source of that Slide, I've tried using `slides[i].shapes[i].part.blob` retrieve the XML source of the GraphFrame Object, but no, it only return the same as the `slides[i].part.blob` returned.

I am not sure if that is possible to retrieve the XML source of the specific shape's which is the SmartObj ?

Thank you Scanny.

**Comment by scanny** [comment] 2018-10-05 16:01
I expect a smart-art is in a separate part from the slide it appears on (possibly more than one separate part). So you would look in the XML for the graphic frame to find a key like 'rId2' and then traverse that relationship to find the target part.

**Comment by alphazw** [comment] 2018-10-07 15:27
Yes, you are correct, I looked into the .pptx file, the source of the smart-art sits inside a folder named 'diagrams', it includes a couple of .xml files depends on how many smart-art in the presentation. and I am guessing each one of the smart-art object in the presentation related to 5 docs in this folder, and they are: colors.xml, data.xml, drawing.xml, layout.xml and quickstyle.xml with index numbers after each of their filename.

**Comment by samredway** [comment] 2019-05-21 05:00
Would also like to request this feature be implemented. I need all the text from a powerpoint slide and manually parsing the XML is kind of yucky.

**Comment by shreyanshu09** [comment] 2024-09-04 05:11
Hi @alphazw @scanny, is there any update regarding getting the text from SmartArt objects?

**Comment by RishitSingh10** [comment] 2024-09-20 09:31
Cannot directly access the smartart objects using pptx library​

Extracting and editing text within smartart objs:​

1. Unzip ppt file -> outputs a folder containing all the meta data for the ppt​
2. Go to ppt/diagrams/ -> This folder contains all the information about smart objects in the ppt​
3. The data.xml file contains the text information used in the smart object​
4. Edit the data.xml file by replacing the original text with edited text​
5. Rezip the file and save as a new .pptx file​

```
def unzip_pptx(pptx_path, extract_dir):
    # Unzip the pptx file
    with zipfile.ZipFile(pptx_path, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)

def edit_smartart_xml(diagram_folder, target_language):

    for root_dir, dirs, files in os.walk(diagram_folder):
        for file in files:
            if file.startswith('data') and file.endswith('.xml'):
                xml_file = os.path.join(root_dir, file)
                tree = ET.parse(xml_file)
                root = tree.getroot()

                for elem in root.iter('{http://schemas.openxmlformats.org/drawingml/2006/main}t'):
                    elem.text = translation_function(elem.text, target_language)
                
                tree.write(xml_file, encoding = 'utf-8', xml_declaration = True)
                print(f"Edited {xml_file}")

def rezip_pptx(extract_dir, output_pptx):
    with zipfile.ZipFile(output_pptx, 'w', zipfile.ZIP_DEFLATED) as pptx_zip:
        for root, dirs, files in os.walk(extract_dir):
            for file in files:
                full_path = os.path.join(root, file)
                arcname = os.path.relpath(full_path, extract_dir)
                pptx_zip.write(full_path, arcname)
```
