### ISSUE TITLE
Unable to Create THREE_D_COLUMN_CLUSTERED Charts in ppt

### ISSUE THREAD

**Issue by srinivas946** [scanny/python-pptx#445] opened 2018-10-02 05:05 UTC
With python pptx i can easily create the 2D charts but when come to 3D Charts i'm unable to do. When i tried to create Chart type as THREE_D_COLUMN_CLUSTERED i'm getting Non Implemented Error(54).
I Want a feature for creating 3D Charts

**Comment by scanny** [comment] 2018-10-02 17:31
Duplicate of #266.

**Closed by scanny** 2018-10-02 17:31 UTC
