### ISSUE TITLE
Support for "application/vnd.ms-office.chartstyle+xml"

### ISSUE THREAD

**Issue by Emn1ty** [scanny/python-pptx#248] opened 2016-12-06 18:56 UTC
After creating a basic Powerpoint file via Microsoft Office (OSX) with an embedded Excel chart, I attempted to open the file with python-pptx and save it just to ensure opening and saving it would still work in Powerpoint. However, I get this error.

```Traceback (most recent call last):
  File "power-point-excel.py", line 6, in <module>
    presentation = Presentation('/Presentation1-test.pptx')
  File "/work/python-ppt/pptx/api.py", line 29, in __init__
    self._package = _Package(file)
  File "/work/python-ppt/pptx/presentation.py", line 96, in __init__
    self.__open(file)
  File "/work/python-ppt/pptx/presentation.py", line 219, in __open
    pkg = pptx.packaging.Package().open(file)
  File "/work/python-ppt/pptx/packaging.py", line 100, in open
    part._load(fs, partname, cti, parts_dict)
  File "/work/python-ppt/pptx/packaging.py", line 256, in _load
    target_part._load(fs, target_partname, ct_dict, parts_dict)
  File "/work/python-ppt/pptx/packaging.py", line 256, in _load
    target_part._load(fs, target_partname, ct_dict, parts_dict)
  File "/work/python-ppt/pptx/packaging.py", line 256, in _load
    target_part._load(fs, target_partname, ct_dict, parts_dict)
  File "/work/python-ppt/pptx/packaging.py", line 240, in _load
    self.typespec = PartTypeSpec(content_type)
  File "/work/python-ppt/pptx/packaging.py", line 517, in __init__
    raise KeyError(tmpl % content_type)
KeyError: "no content type 'application/vnd.ms-office.chartstyle+xml' in pptx.spec.pml_parttypes"
```

It seems that the content type produced by my version of Office's Powerpoint isn't supported?

Application information: Microsoft Powerpoint for Mac Version 15.27 (161010)

The Powerpoint document does have an embedded Excel chart in it.

**Comment by scanny** [comment] 2016-12-06 21:44
What PowerPoint version is that in terms of what it shows on the screen or whatever? Like PowerPoint 2011? Maybe PowerPoint 2015?

Also, what version is the Excel you're using? Anything distinctive about the chart? Do you have chart styles defined on your machine that you might be using in the chart (perhaps located in the ~/Library/Application Support/Microsoft/Office/..something templates  directory, possibly a .crtx file)?

I think we can fix this just with adding a content type, but I'd like to have an idea why it's showing up suddenly.

Can you provide a small-as-possible example .pptx file that exhibits this behavior? I'd like to look under its hood and see what type of parts the package contains. There must be a chart style part or something in there.

**Comment by scanny** [comment] 2016-12-06 22:08
Okay, some research seems to indicate this is a new part type that has been added (without benefit of documentation :). If you send over the example I'll investigate further. There's a new revision of the ISO/IEC 29500 spec (2016 version). It doesn't mention it but perhaps the .xsd and other "electronic inserts" it comes with will shed some light.

**Comment by scanny** [comment] 2016-12-09 20:54
@Emn1ty Any response on this one? I'll be pushing a new release here in a few days and if this turns out to be simple (as I think it may) I'd like to include getting this working as it's bound to come up for other folks as they get to newer versions.

**Comment by Emn1ty** [comment] 2016-12-09 21:17
Hey @scanny, my apologies as it has been quite hectic at work recently and just haven't noticed this. To answer your request I the sample files here: [SamplePPT.zip](https://github.com/scanny/python-pptx/files/643219/SamplePPT.zip)

I was looking into this because I was attempting to use python-pptx to embed linked charts from excel into powerpoint. Hope these files help though :)

**Comment by scanny** [comment] 2017-01-03 21:57
Okay, for some reason I can't reproduce this error, but I did add a small handful of Microsoft extension content types I found, including this Chart Style part type. We'll see how we go :)

This will be in the release later today, v0.6.2.

**Closed by scanny** 2017-01-03 21:57 UTC
Labels: package, shortlist
