### ISSUE TITLE
feature: create_slide(slideNumber) copy_slide(slideNumber)

### ISSUE THREAD

**Issue by rocker19943** [scanny/python-pptx#217] opened 2016-06-28 08:58 UTC
Hi,

It's highly desired to have a function to create and copy a slide by slide number, current add_slide is just adding a new slide in the end of the pptx,

I have to generate some new information and create a new slide in the middle of presentation and insert that data in there, since that slide has a spcefic table which cannot be generated using this API i have to copy that slide to fit all generated data in it.

Currently i've made a workaround for me but it's have to be adjusted every time when there are new changes in the template.

I'm using this api for 2 years and still waiting for these functions. Kindly asking you to finally implement these very useful features.

Thanks

**Comment by scanny** [comment] 2017-04-24 19:16
Duplicate of #194 and #132.

**Closed by scanny** 2017-04-24 19:16 UTC
Labels: slide
