### ISSUE TITLE
Use a image as Slide background

### ISSUE THREAD

**Issue by zjrn** [scanny/python-pptx#543] opened 2019-08-20 09:51 UTC
How can i use a image as the background picture of Slide?

**Comment by kewbish** [comment] 2019-09-16 14:57
What I did is insert a picture placeholder in the template, and move that picture to back. Then, I could set the picture using python-pptx.

**Comment by scanny** [comment] 2021-08-11 19:40
Duplicate of #366

**Closed by scanny** 2021-08-11 19:40 UTC
