### ISSUE TITLE
Is it possible to set an image as the background of the slide ?

### ISSUE THREAD

**Issue by antoinebattagliotti** [scanny/python-pptx#496] opened 2019-04-19 12:38 UTC
I am currently working on a project aiming to create a PowerPoint thanks Python pptx. However I am trying to set an image as the background of the slide and I can’t seem to find the solution in the docs of Python pptx. Is it possible to set an image as background if so can someone help me ?

**Comment by Motta23** [comment] 2019-05-09 20:06
What you can do is insert an image, with the same width and the height of the slide, effectively creating a background image:
```
prs = Presentation()
title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)
left = top = Inches(0)
img_path = declare_your_image_path.jpg
pic = slide.shapes.add_picture(img_path, left, top, width=prs.slide_width, height=prs.slide_height)

# This moves it to the background
slide.shapes._spTree.remove(pic._element)
slide.shapes._spTree.insert(2, pic._element)
```

**Comment by ROOKIE20570** [comment] 2020-10-28 12:52
> width

work for me !

**Comment by scanny** [comment] 2021-08-11 19:40
Duplicate of #366

**Closed by scanny** 2021-08-11 19:40 UTC
