### ISSUE TITLE
Add slide to the middle of an existing presentation

### ISSUE THREAD

**Issue by BehnamKS** [scanny/python-pptx#325] opened 2017-10-24 12:09 UTC
Hi everyone,

-I'm trying to add slide to the middle of an existing presentation

-What happens with my code now is that it adds the new slide to the end of the existing presentation

Would be happy if anyone knows the solution
Cheers

**Comment by hpsiepsi** [comment] 2017-10-31 18:19
I too would appreciate this as my typical template has default opening and closing slides, but it isn't a huge priority for me as I can always change it in PPT after saving.

**Comment by scanny** [comment] 2017-10-31 18:31
@hpsiepsi One approach to standard opening (title) and closing slides is to make a slide layout for each and use those to create the title and closing slide in each new presentation. There's nothing preventing you from using a new slide with no changes beyond what comes in the layout. My standard corporate template does just that for the closing slide (the opening slide has a placeholder for presentation title and author).

As far as I know, there is nothing you can put on a slide that you can't also put on a layout. That might be an approach to consider.

**Comment by MartinPacker** [comment] 2018-01-02 16:02
Well, I would like to add a Table Of Contents Slide - after the first Title slide.

But, unless I implement two-pass over my source data (Markdown), I won't have the contents for the TOC slide soon enough. In this case an "insert slide after" or "insert slide before" would be handy.

**Comment by scanny** [comment] 2018-01-02 17:51
Duplicate of #194.

**Closed by scanny** 2018-01-02 17:51 UTC
