### ISSUE TITLE
How to send image back?

### ISSUE THREAD

**Issue by shalakhin** [scanny/python-pptx#195] opened 2016-01-27 16:56 UTC
Hi guys!

How to send image back on the slide?

**Comment by shalakhin** [comment] 2016-01-27 17:40
Already found in one of issues here. 

```
cover_bg = slide.shapes.add_picture(company.cover_background, left, top)
slide.shapes._spTree.remove(cover_bg._element)
slide.shapes._spTree.insert(2, cover_bg._element)
```

**Comment by scanny** [comment] 2016-01-27 18:00
Are you looking to change the z-order of the picture shape or actually use it as the slide background? These are two different things, each with its own mechanism.

**Comment by shalakhin** [comment] 2016-01-27 18:02
Ideally I would like to set background image.

**Comment by shalakhin** [comment] 2016-01-28 22:24
@scanny how can I set background image for slides?

**Comment by rmithun** [comment] 2016-10-05 12:24
@shalakhin if you need to set the image as background one unclear solution is scaling the picture to the size of slide. like below

left = top = Inches(0)
slide.shapes.add_picture(img_path, left, top, width=prs.slide_width, height=prs.slide_height)

not sure whether this might be helpful to you.

**Comment by zjrn** [comment] 2019-08-20 09:10
> Are you looking to change the z-order of the picture shape or actually use it as the slide background? These are two different things, each with its own mechanism.

How to use a image as the background of slide please?

**Comment by scanny** [comment] 2021-08-11 19:41
Duplicate of #366

**Closed by scanny** 2021-08-11 19:41 UTC
Labels: slide
