### ISSUE TITLE
Save as PDF possible?

### ISSUE THREAD

**Issue by markw-** [scanny/python-pptx#324] opened 2017-10-24 11:57 UTC
Hi Scanny,

I'm working on something where I have to save individual slides (about 140
of them) in PDF format - probably every month. Is there a way to do this
or could this be added to python-pptx?

Sorry for not posting to the Google group - I have reservations about the ethics of that organisation and avoid them when-ever possible.

All the best
Mark

**Comment by scanny** [comment] 2017-10-24 19:01
Closing as duplicate of #271.

**Closed by scanny** 2017-10-24 19:01 UTC
